vich_uploader:
    db_driver: orm

    mappings:
        client_image:
            uri_prefix: /clients/images
            upload_destination: '%kernel.project_dir%/public/clients/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
#    mappings:
#        products:
#            uri_prefix: /images/products
#            upload_destination: '%kernel.project_dir%/public/images/products'
